from pathlib import Path
import html, json, re

ROOT=Path(__file__).resolve().parents[1]
BASE='https://viajescasal-sketch.github.io/elkitdelviajero'

articles=[
('accesorios-indispensables-para-viajar','Los accesorios indispensables para viajar','Equipaje','Una selección práctica para viajar más cómodo, organizado y seguro.',['Prioriza lo que resuelve problemas reales: energía, orden, seguridad y comodidad.','Empieza con una mochila de cabina, organizadores, power bank, candado TSA y una báscula compacta.','Adapta el kit al destino, la duración y si documentarás equipaje.'],['mochilas','organizadores','powerbanks']),
('que-llevar-a-cancun','Qué llevar a Cancún','Playa','Lista práctica para disfrutar el Caribe sin cargar de más.',['Empaca ropa ligera, dos trajes de baño, protección solar y calzado que pueda mojarse.','Lleva una bolsa impermeable, botellas rellenables de viaje y organizadores para separar ropa húmeda.','Deja espacio para una capa ligera: transportes y restaurantes suelen tener aire acondicionado.'],['organizadores','powerbanks']),
('que-llevar-a-europa','Qué llevar a Europa','Internacional','Equipaje, documentos y tecnología para un viaje europeo sin imprevistos.',['Revisa la temporada en cada ciudad y construye conjuntos por capas que combinen entre sí.','Guarda copias de pasaporte, reservas y seguro; distribúyelas entre equipaje y almacenamiento seguro.','Un adaptador universal, power bank y mochila cómoda resuelven gran parte del día a día.'],['adaptadores','mochilas','powerbanks']),
('como-organizar-una-maleta','Cómo organizar una maleta','Equipaje','Método paso a paso para aprovechar espacio y encontrar todo rápido.',['Haz una lista por actividades y elimina prendas que no formen al menos dos conjuntos.','Agrupa por categorías en organizadores y coloca lo pesado junto a las ruedas.','Reserva un módulo para ropa usada y pesa la maleta antes de salir.'],['organizadores','candados-tsa']),
('equipaje-permitido-por-aerolinea','Equipaje permitido por aerolínea','Equipaje','Cómo verificar medidas, peso y restricciones antes de llegar al aeropuerto.',['Consulta siempre la tarifa exacta de tu reservación: una aerolínea puede tener reglas distintas por boleto.','Mide incluyendo ruedas y asas; pesa el equipaje con una báscula antes de salir.','Baterías de litio y power banks suelen viajar en cabina, sujetos a límites de la aerolínea.'],['mochilas','powerbanks']),
('como-evitar-pagar-sobrepeso','Cómo evitar pagar sobrepeso','Consejos de viaje','Estrategias sencillas para reducir peso y cargos en el aeropuerto.',['Pesa cada pieza en casa y deja un margen para diferencias entre básculas.','Distribuye objetos densos, usa envases pequeños y evita duplicar artículos disponibles en el hotel.','Compara el costo de añadir equipaje en línea antes del aeropuerto.'],['organizadores']),
('mejores-power-banks-para-viajar','Los mejores power banks para viajar','Internacional','Qué capacidad, puertos y seguridad conviene buscar.',['Para un día normal, 10,000 mAh ofrece buen equilibrio entre tamaño y autonomía.','Busca USB-C Power Delivery, indicador claro de carga y certificaciones de seguridad.','Confirma el límite de la aerolínea y transporta la batería en equipaje de mano.'],['powerbanks']),
('mejores-mochilas-de-cabina','Las mejores mochilas de cabina','Mochilero','Cómo elegir capacidad, apertura y comodidad sin exceder medidas.',['Compara las medidas externas con el límite de tu tarifa, no solo los litros anunciados.','La apertura tipo maleta facilita empacar; las correas acolchadas importan si caminarás mucho.','Prefiere materiales resistentes, cierres confiables y un compartimento accesible para documentos.'],['mochilas','candados-tsa']),
('checklist-para-viajar-en-avion','Checklist para viajar en avión','Documentación','Todo lo que conviene revisar desde 48 horas antes hasta el abordaje.',['Confirma horario, terminal, documentos y equipaje incluido en tu tarifa.','Descarga pases de abordar y reservas para consultarlos sin conexión.','En cabina lleva medicamentos, documentos, cargadores y una muda esencial.'],['mochilas','powerbanks']),
('que-llevar-si-viajas-con-ninos','Qué llevar si viajas con niños','Familia','Una lista realista para trayectos más tranquilos en familia.',['Prepara un cambio completo por niño, snacks permitidos y entretenimiento sin conexión.','Agrupa medicamentos y documentos en un estuche accesible para el adulto responsable.','Usa organizadores por persona y evita repartir objetos esenciales en una sola maleta documentada.'],['organizadores','mochilas']),
]

landings={
'mochilas':('Mochilas de cabina para viajar','Elige una mochila compatible con tu forma de viajar y con las medidas de tu tarifa.',['Medidas exteriores adecuadas','Apertura tipo maleta','Correas cómodas y ajustables','Compartimento seguro para documentos']),
'powerbanks':('Power banks para viajar','Mantén disponibles mapas, reservas y comunicación durante traslados y escalas.',['Capacidad equilibrada','Carga USB-C rápida','Indicador de batería','Transporte seguro en cabina']),
'adaptadores':('Adaptadores universales de viaje','Conecta tus dispositivos en destinos internacionales con mayor facilidad.',['Clavijas para varios destinos','Puertos USB-C y USB-A','Protección integrada','Diseño compacto']),
'candados-tsa':('Candados TSA para equipaje','Añade una capa práctica de seguridad a maletas y mochilas.',['Combinación configurable','Indicador de inspección','Cuerpo resistente','Tamaño fácil de transportar']),
'organizadores':('Organizadores de maleta','Separa categorías, aprovecha espacio y encuentra todo sin deshacer la maleta.',['Varios tamaños','Cierres resistentes','Malla para identificar contenido','Bolsa para ropa usada']),
}

guides=[('checklist-playa','Checklist para playa','Sol, agua, ropa ligera y accesorios para mantener todo seco.'),('checklist-internacional','Checklist internacional','Documentos, dinero, conectividad y seguridad antes de salir del país.'),('checklist-europa','Checklist Europa','Capas, adaptadores, traslados y documentación para recorrer varias ciudades.'),('checklist-disney','Checklist Disney','Mochila de parque, clima, batería y esenciales para aprovechar el día.'),('checklist-viaje-con-ninos','Checklist viaje con niños','Documentos, cambios, entretenimiento, snacks y salud familiar.')]

article_images={
'accesorios-indispensables-para-viajar':('https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=84','Mochila y accesorios preparados para viajar'),
'que-llevar-a-cancun':('https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=84','Playa de arena blanca y mar turquesa en Cancún'),
'que-llevar-a-europa':('https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1200&q=84','Viaje por una ciudad europea'),
'como-organizar-una-maleta':('https://images.unsplash.com/photo-1581553680321-4fffae59fccd?auto=format&fit=crop&w=1200&q=84','Equipaje organizado antes de viajar'),
'equipaje-permitido-por-aerolinea':('https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=84','Avión preparado para despegar'),
'como-evitar-pagar-sobrepeso':('https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=1200&q=84','Maleta lista para revisar su peso'),
'mejores-power-banks-para-viajar':('https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=1200&q=84','Batería portátil para viajar'),
'mejores-mochilas-de-cabina':('https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=84','Mochila compacta para equipaje de cabina'),
'checklist-para-viajar-en-avion':('https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=84','Preparativos para un viaje en avión'),
'que-llevar-si-viajas-con-ninos':('https://images.unsplash.com/photo-1504150558240-0b4fd8946624?auto=format&fit=crop&w=1200&q=84','Familia disfrutando un viaje con niños')}

def esc(s): return html.escape(s)
def header(title,desc,path,schema=''):
 depth='../'*(path.count('/')+1)
 return f'''<!doctype html><html lang="es-MX"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)} | El Kit del Viajero</title><meta name="description" content="{esc(desc)}"><link rel="canonical" href="{BASE}/{path}/"><meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(desc)}"><meta property="og:type" content="article"><meta property="og:url" content="{BASE}/{path}/"><link rel="stylesheet" href="{depth}assets/recursos.css">{schema}</head><body><div class="announcement">✈️ Recursos prácticos seleccionados por Viajes Casal</div><header class="site-header"><div class="container nav"><a class="brand" href="{depth}index.html">EL KIT DEL VIAJERO<small>BY VIAJES CASAL</small></a><nav class="nav-links"><a href="{depth}blog/index.html">Centro de recursos</a><a href="{depth}guias/index.html">Guías gratis</a><a class="button" href="{depth}index.html#productos">Ver productos</a></nav></div></header>'''
def footer(depth='../'):
 return f'''<footer class="footer"><div class="container footer-row"><div><strong>El Kit del Viajero</strong><br><small>Recursos de viaje por Viajes Casal</small></div><div><a href="{depth}blog/index.html">Blog</a> · <a href="{depth}guias/index.html">Guías</a> · <a href="{depth}index.html#preguntas">Preguntas</a></div></div></footer><script src="{depth}assets/recursos.js" defer></script></body></html>'''

def schema_article(title,desc,slug,faqs):
 data={'@context':'https://schema.org','@type':'Article','headline':title,'description':desc,'inLanguage':'es-MX','mainEntityOfPage':f'{BASE}/blog/{slug}/','author':{'@type':'Organization','name':'Viajes Casal'},'publisher':{'@type':'Organization','name':'El Kit del Viajero by Viajes Casal'},'datePublished':'2026-07-15','dateModified':'2026-07-15'}
 faq={'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in faqs]}
 return '<script type="application/ld+json">'+json.dumps(data,ensure_ascii=False)+'</script><script type="application/ld+json">'+json.dumps(faq,ensure_ascii=False)+'</script>'

for slug,title,cat,desc,points,products in articles:
 image_url,image_alt=article_images[slug]
 faqs=[(f'¿Qué es lo más importante al preparar {title.lower()}?',points[0]),('¿Cuándo conviene revisar esta lista?','Revísala al reservar, una semana antes y nuevamente 24 horas antes de salir.'),('¿Debo comprar todos los accesorios?','No. Prioriza únicamente lo que resuelva una necesidad concreta de tu viaje.')]
 sections=[('Planifica según tu viaje',points[0]),('Organiza lo esencial',points[1]),('Revisión antes de salir',points[2])]
 toc=''.join(f'<a href="#s{i}">{esc(h)}</a>' for i,(h,_) in enumerate(sections,1))
 body=''.join(f'<h2 id="s{i}">{esc(h)}</h2><p>{esc(p)}</p><p>Convierte esta recomendación en una decisión concreta: revisa lo que ya tienes, confirma las reglas de tu transporte y lleva solo aquello que usarás. Una preparación sencilla suele funcionar mejor que empacar para todos los escenarios posibles.</p>' for i,(h,p) in enumerate(sections,1))
 links=' '.join(f'<a class="chip" href="../../{p}/index.html">{landings[p][0]}</a>' for p in products)
 related=''.join(f'<a class="chip" href="../{a[0]}/index.html">{a[1]}</a>' for a in articles if a[0]!=slug)[:1200]
 page=header(title,desc,f'blog/{slug}',schema_article(title,desc,slug,faqs))+f'''<div class="container breadcrumbs"><a href="../../index.html">Inicio</a> / <a href="../">Centro de recursos</a> / {esc(cat)}</div><section class="hero"><div class="container"><span class="eyebrow">{esc(cat)}</span><h1>{esc(title)}</h1><p>{esc(desc)}</p><div class="meta" style="color:#c7e8ed">Lectura estimada: 5 minutos · Actualizado el 15 de julio de 2026</div></div></section><main class="section"><div class="container article-layout"><article class="article-body"><div class="callout"><strong>En pocas palabras:</strong> {esc(' '.join(points))}</div>{body}<div class="product-cta"><h3>Arma tu kit</h3><p>Explora las categorías relacionadas y compara opciones según tu viaje.</p>{links}</div><h2 id="preguntas">Preguntas frecuentes</h2><div class="faq">{''.join(f'<details><summary>{esc(q)}</summary><p>{esc(a)}</p></details>' for q,a in faqs)}</div><h2>Continúa preparando tu viaje</h2><div class="chips">{related}</div></article><aside class="toc"><strong>En esta guía</strong>{toc}<a href="#preguntas">Preguntas frecuentes</a><a href="../../guias/">Descargar checklists</a></aside></div></main>'''+footer('../../')
 page=page.replace('<article class="article-body">',f'<article class="article-body"><img class="feature-image" src="{image_url}" alt="{esc(image_alt)}" loading="eager"><p class="image-caption">Inspiración práctica para preparar tu próximo viaje.</p>')
 out=ROOT/'blog'/slug/'index.html';out.parent.mkdir(parents=True,exist_ok=True);out.write_text(page,encoding='utf-8')

cards=''.join(f'''<article class="card has-image"><img class="card-image" src="{article_images[slug][0]}" alt="{esc(article_images[slug][1])}" loading="lazy"><div class="card-content"><span class="kicker" style="color:var(--turquoise)">{esc(cat)}</span><h3>{esc(title)}</h3><p>{esc(desc)}</p><span class="meta">5 min de lectura</span><a href="{slug}/index.html">Leer guía →</a></div></article>''' for slug,title,cat,desc,_,_ in articles)
cats=[('✈️','Equipaje'),('🌴','Playa'),('🌍','Internacional'),('👨‍👩‍👧','Familia'),('💼','Negocios'),('🎒','Mochilero'),('💳','Documentación'),('🏨','Consejos de viaje')]
catcards=''.join(f'<div class="card"><span class="category-icon">{icon}</span><h3>{name}</h3><p>Consejos, listas y productos recomendados para viajar mejor.</p></div>' for icon,name in cats)
blog=header('Centro de Recursos para Viajeros','Guías prácticas, checklists y recomendaciones para preparar cada tipo de viaje.','blog')+f'''<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">Centro de recursos</span><h1>Planea mejor. Empaca menos. Viaja tranquilo.</h1><p>Respuestas concretas para organizar equipaje, documentos, tecnología y viajes en familia.</p></div><div class="hero-card"><strong>10 guías prácticas</strong><p>Contenido útil conectado con checklists descargables y categorías de producto.</p><a class="button button-secondary" href="../guias/">Descargar guías</a></div></div></section><main><section class="section alt"><div class="container"><header class="section-head"><span class="kicker" style="color:var(--turquoise)">Explora por categoría</span><h2>Recursos para cada forma de viajar</h2></header><div class="grid">{catcards}</div></div></section><section class="section"><div class="container"><header class="section-head"><span class="kicker" style="color:var(--turquoise)">Artículos destacados</span><h2>Empieza por estas guías</h2></header><div class="grid">{cards}</div></div></section></main>'''+footer('../')
blog=blog.replace('<div class="grid"><article class="card has-image">','<div class="article-carousel" aria-label="Artículos destacados"><article class="card has-image">')
(ROOT/'blog').mkdir(exist_ok=True);(ROOT/'blog'/'index.html').write_text(blog,encoding='utf-8')

for slug,(title,desc,features) in landings.items():
 relevant=[a for a in articles if slug in a[5]][:3]
 rel=''.join(f'<article class="card"><h3>{a[1]}</h3><p>{a[3]}</p><a href="../blog/{a[0]}/index.html">Leer guía →</a></article>' for a in relevant)
 product_schema={'@context':'https://schema.org','@type':'CollectionPage','name':title,'description':desc,'url':f'{BASE}/{slug}/'}
 page=header(title,desc,slug,'<script type="application/ld+json">'+json.dumps(product_schema,ensure_ascii=False)+'</script>')+f'''<div class="container breadcrumbs"><a href="../index.html">Inicio</a> / {esc(title)}</div><section class="hero"><div class="container hero-grid"><div><span class="eyebrow">Selección del viajero</span><h1>{esc(title)}</h1><p>{esc(desc)}</p><a class="button button-secondary" href="../index.html#productos">Comparar productos</a></div><div class="hero-card"><strong>Qué revisar antes de elegir</strong><ul>{''.join(f'<li>{esc(x)}</li>' for x in features)}</ul></div></div></section><main><section class="section"><div class="container"><header class="section-head"><h2>Cómo elegir</h2><p>No existe una única opción para todos. Compara dimensiones, materiales, compatibilidad y condiciones de venta con las necesidades de tu próximo viaje.</p></header><ul class="checklist">{''.join(f'<li><strong>{esc(x)}:</strong> comprueba este punto en la publicación antes de comprar.</li>' for x in features)}</ul></div></section><section class="section alt"><div class="container"><header class="section-head"><h2>Guías relacionadas</h2></header><div class="grid">{rel}</div></div></section></main>'''+footer('../')
 out=ROOT/slug/'index.html';out.parent.mkdir(exist_ok=True);out.write_text(page,encoding='utf-8')

guide_cards=''.join(f'''<article class="card has-image"><img class="card-image" src="{article_images[list(article_images)[i]][0]}" alt="Imagen para {esc(title)}" loading="lazy"><div class="card-content"><span class="category-icon">📄</span><h3>{esc(title)}</h3><p>{esc(desc)}</p><span class="meta">PDF gratuito · 2 páginas</span></div></article>''' for i,(slug,title,desc) in enumerate(guides))
downloads=''.join(f'<a class="download-link" data-download href="../output/pdf/{slug}.pdf" download>Descargar {esc(title)} →</a>' for slug,title,_ in guides)
guidepage=header('Guías descargables para viajar','Checklists gratuitas para playa, Europa, Disney, viajes internacionales y viajes con niños.','guias')+f'''<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">Biblioteca gratuita</span><h1>Checklists listas para tu próximo viaje</h1><p>Guarda las guías en tu celular o imprímelas para preparar cada detalle con tiempo.</p></div><div class="hero-card"><strong>5 guías en PDF</strong><p>Prácticas, breves y diseñadas para marcar.</p></div></div></section><main><section class="section"><div class="container"><div class="grid">{guide_cards}</div></div></section><section class="section alt"><div class="container"><div class="lead-box"><span class="kicker" style="color:var(--turquoise)">Acceso gratuito</span><h2>Recibe todas las checklists</h2><p>Escribe tu correo para desbloquear las cinco descargas. Tu configuración de email marketing puede conectarse después en <code>assets/recursos.js</code>.</p><form class="lead-form" data-lead-form data-guide="biblioteca-sprint-2"><input type="email" name="email" placeholder="tu@email.com" required aria-label="Correo electrónico"><button class="button" type="submit">Desbloquear guías</button><div class="form-message" aria-live="polite"></div><div class="download-list">{downloads}</div></form></div></div></section></main>'''+footer('../')
guidepage=guidepage.replace('<div class="grid"><article class="card has-image">','<div class="article-carousel" aria-label="Guías descargables"><article class="card has-image">')
out=ROOT/'guias'/'index.html';out.parent.mkdir(exist_ok=True);out.write_text(guidepage,encoding='utf-8')

sitemap=['', 'aviso-privacidad.html', 'blog/','guias/']+[f'blog/{a[0]}/' for a in articles]+[f'{x}/' for x in landings]
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'<url><loc>{BASE}/{p}</loc><lastmod>2026-07-15</lastmod></url>\n' for p in sitemap)+'</urlset>',encoding='utf-8')
(ROOT/'robots.txt').write_text(f'User-agent: *\nAllow: /\nSitemap: {BASE}/sitemap.xml\n',encoding='utf-8')
print(f'Generated {len(articles)} articles, {len(landings)} landings and resource hubs.')
